title: Poonguzhali Vijayakumar # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Product Manager
  <br><br>
  <a href="mailto:kvpoonguzhali@gmail.com">kvpoonguzhali@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/poonguzhalivijayakumar/">LinkedIn Profile</a>
  <br>
theme: jekyll-theme-minimal
